//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.SqlServerDao.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ObrasEntities : DbContext
    {
        public ObrasEntities()
            : base("name=ObrasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Requirement> Requirement { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sheet> Sheet { get; set; }
        public virtual DbSet<SheetItem> SheetItem { get; set; }
        public virtual DbSet<SheetState> SheetState { get; set; }
        public virtual DbSet<SubItem> SubItem { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
