//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.SqlServerDao.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sheet()
        {
            this.SheetItem = new HashSet<SheetItem>();
        }
    
        public int requirementNumber { get; set; }
        public int sheetNumber { get; set; }
        public int sheetStateId { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime untilDate { get; set; }
        public string observation { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual SheetState SheetState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SheetItem> SheetItem { get; set; }
    }
}
